In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.0.0


# 加载模型看model.trai

In [2]:
model = tf.keras.applications.VGG16(False)

In [10]:
len(model.trainable_weights), len(model.trainable_variables)

(26, 26)

In [14]:
model.trainable_weights[0]

<tf.Variable 'block1_conv1/kernel:0' shape=(3, 3, 3, 64) dtype=float32, numpy=
array([[[[ 4.29470569e-01,  1.17273867e-01,  3.40129584e-02, ...,
          -1.32241577e-01, -5.33475243e-02,  7.57738389e-03],
         [ 5.50379455e-01,  2.08774377e-02,  9.88311544e-02, ...,
          -8.48205537e-02, -5.11389151e-02,  3.74943428e-02],
         [ 4.80015397e-01, -1.72696680e-01,  3.75577137e-02, ...,
          -1.27135560e-01, -5.02991639e-02,  3.48965675e-02]],

        [[ 3.73466998e-01,  1.62062630e-01,  1.70863140e-03, ...,
          -1.48207128e-01, -2.35300660e-01, -6.30356818e-02],
         [ 4.40074533e-01,  4.73412387e-02,  5.13819456e-02, ...,
          -9.88498852e-02, -2.96195745e-01, -7.04357103e-02],
         [ 4.08547401e-01, -1.70375049e-01, -4.96297423e-03, ...,
          -1.22360572e-01, -2.76450396e-01, -3.90796512e-02]],

        [[-6.13601133e-02,  1.35693997e-01, -1.15694344e-01, ...,
          -1.40158370e-01, -3.77666801e-01, -3.00509870e-01],
         [-8.13870355

In [15]:
model.trainable_variables[0]

<tf.Variable 'block1_conv1/kernel:0' shape=(3, 3, 3, 64) dtype=float32, numpy=
array([[[[ 4.29470569e-01,  1.17273867e-01,  3.40129584e-02, ...,
          -1.32241577e-01, -5.33475243e-02,  7.57738389e-03],
         [ 5.50379455e-01,  2.08774377e-02,  9.88311544e-02, ...,
          -8.48205537e-02, -5.11389151e-02,  3.74943428e-02],
         [ 4.80015397e-01, -1.72696680e-01,  3.75577137e-02, ...,
          -1.27135560e-01, -5.02991639e-02,  3.48965675e-02]],

        [[ 3.73466998e-01,  1.62062630e-01,  1.70863140e-03, ...,
          -1.48207128e-01, -2.35300660e-01, -6.30356818e-02],
         [ 4.40074533e-01,  4.73412387e-02,  5.13819456e-02, ...,
          -9.88498852e-02, -2.96195745e-01, -7.04357103e-02],
         [ 4.08547401e-01, -1.70375049e-01, -4.96297423e-03, ...,
          -1.22360572e-01, -2.76450396e-01, -3.90796512e-02]],

        [[-6.13601133e-02,  1.35693997e-01, -1.15694344e-01, ...,
          -1.40158370e-01, -3.77666801e-01, -3.00509870e-01],
         [-8.13870355

# <font face="Times New Roman">tf.Varible</font>

In [29]:
a  = tf.Variable(3.,trainable=False)
a.trainable

False

In [36]:
mean = tf.constant([0.491, 0.482, 0.447])
std = tf.constant([0.247, 0.243, 0.262])
paddings = tf.constant([[4, 4], [4, 4], [0, 0]])
x = tf.ones([32,32,3])
x = tf.cast(x, dtype=tf.float32)
x = (x - mean) / std
x = tf.pad(x, paddings)
x = tf.image.random_crop(x, [32,32,3])
x = tf.image.random_flip_up_down(x)
print(x[:10,:10,0])

tf.Tensor(
[[0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.       ]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607288
  2.0607288 2.0607288 2.0607288]
 [2.0607288 2.0607288 2.0607288 2.0607288 2.0607288 2.0607

In [22]:
data = tf.ones([32,32,3])
paddings = tf.constant([[4,4], [4,4],[0,0]])
data = tf.pad(data, paddings)
x = tf.image.random_crop(data, [32,32,3])
tf.math.reduce_sum(tf.math.abs(x[:,:,1] - x[:,:,0]))

<tf.Tensor: id=436, shape=(), dtype=float32, numpy=0.0>

# <font face="Times New Roman">测试TensorFlow的tf.data.Dataset的map,证明map的时候应该是一口气对数据进行预处理的</font>
```python
data = tf.ones([10,10])
dataset = tf.data.Dataset.from_tensor_slices(data)
print(f'map之前:{list(dataset)[0]}')
# map之前:[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
dataset = dataset.map(lambda x:x+1)
print(f'map之后:{list(dataset)[0]}')
# map之后:[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
```

In [7]:
data = tf.ones([10,10])
dataset = tf.data.Dataset.from_tensor_slices(data)
print(f'map之前:{list(dataset)[0]}')
dataset = dataset.map(lambda x:x+1)
print(f'map之后:{list(dataset)[0]}')

map之前:[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
map之后:[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


# 测试map